version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    networks:
      - bot-hub

  db:
    image: postgres:latest
    container_name: 'db'
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./backup/:/backup/
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5438:5432'
    networks:
      - bot-hub

  frontend:
    build: ./client
    container_name: 'frontend'
    env_file:
      - ./client/.env
    ports:
      - '25555:25555'
    command: yarn dev
    volumes:
      - ./client:/app
      - '/app/node_modules'
    depends_on:
      - backend
    networks:
      - bot-hub

  backend:
    image: backend
    build:
      context: ./server
    env_file:
      - ./server/.env
    container_name: 'backend'
    ports:
      - 25556:25556
    command: yarn dev
    restart: unless-stopped
    volumes:
      - ./server/:/app/
      - /app/node_modules
    depends_on:
      - db
    networks:
      - bot-hub

volumes:
  pgdata:

networks:
  bot-hub:
