version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '8080:80'
    depends_on:
      - backend
      - frontend
      - storybook
    networks:
      - bot-hub

  db:
    image: postgres:latest
    container_name: 'db'
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bothub
    volumes:
      - ./backup/:/backup/
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5438:5432'
    networks:
      - bot-hub

  frontend:
    build: ./client
    container_name: 'frontend'
    env_file:
      - ./client/.env
    ports:
      - '25555:25555'
    command: /bin/sh -c "yarn install && yarn dev"
    volumes:
      - ./client:/app
      - '/app/node_modules'
    depends_on:
      - backend
    networks:
      - bot-hub

  storybook:
    build: ./client
    container_name: 'storybook'
    command: /bin/sh -c "yarn install && yarn storybook --no-open"
    ports:
      - '6006:6006'
    volumes:
      - ./client:/app
      - '/app/node_modules'
    depends_on:
      - frontend
    networks:
      - bot-hub

  backend:
    image: backend
    build:
      context: ./server
    env_file:
      - ./server/.env
    container_name: 'backend'
    ports:
      - '25556:25556'
    entrypoint: /bin/sh
    command: -c "yarn install && npx prisma migrate dev && yarn dev"
    restart: unless-stopped
    volumes:
      - ./server/:/app/
      - /app/node_modules
    depends_on:
      - db
    networks:
      - bot-hub

volumes:
  pg_data:

networks:
  bot-hub:
